// Tailwind CSS v4 is CSS-first, but keeping this file helps ecosystem tools
// that still probe for a Tailwind config in existing projects.
const config = {
  darkMode: "class",
  theme: {
    extend: {
      colors: {
        "on-error-container": "#ffb2b9",
        "outline-variant": "#444853",
        "on-primary-fixed-variant": "#632c00",
        "on-secondary": "#000379",
        "on-surface": "#ebedfc",
        "primary-fixed": "#fd9b5c",
        secondary: "#8c94ff",
        "error-container": "#a70138",
        "on-secondary-fixed-variant": "#3c44ae",
        "secondary-dim": "#8c94ff",
        "on-tertiary-fixed": "#370020",
        "on-tertiary": "#5b0038",
        "surface-container": "#151925",
        error: "#ff6e84",
        tertiary: "#ff81bd",
        "surface-dim": "#0a0e18",
        "surface-container-lowest": "#000000",
        background: "#0a0e18",
        "inverse-on-surface": "#515561",
        "on-secondary-fixed": "#1b2292",
        surface: "#0a0e18",
        "surface-tint": "#fd9b5c",
        "on-tertiary-fixed-variant": "#730048",
        "surface-container-low": "#0f131e",
        "inverse-surface": "#faf8ff",
        "tertiary-dim": "#ff66b4",
        "on-primary-fixed": "#311200",
        "surface-variant": "#202534",
        "on-surface-variant": "#a8aab8",
        "on-tertiary-container": "#450029",
        "surface-container-high": "#1b1f2d",
        "on-primary": "#552500",
        "tertiary-container": "#ff66b4",
        "tertiary-fixed-dim": "#ff72b7",
        "on-background": "#ebedfc",
        primary: "#fd9b5c",
        "tertiary-fixed": "#ff8bc1",
        "primary-container": "#e6894c",
        "on-primary-container": "#3d1800",
        "on-secondary-container": "#caccff",
        "primary-dim": "#ed8e51",
        "on-error": "#490013",
        "secondary-fixed": "#ccceff",
        "primary-fixed-dim": "#ed8e51",
        "inverse-primary": "#964a10",
        "secondary-fixed-dim": "#bbbfff",
        "secondary-container": "#3139a4",
        "surface-bright": "#262c3c",
        "surface-container-highest": "#202534",
        "error-dim": "#d73357",
        outline: "#727582",
      },
      borderRadius: { DEFAULT: "0.5rem", lg: "1rem", xl: "1.5rem", full: "9999px" },
      fontFamily: { headline: ["Be Vietnam Pro"], body: ["Geist"], label: ["Lexend"], display: "Be Vietnam Pro" },
    },
  },
};
export default config;
